

INSERT INTO WorkFlow (DataInclusao,EmailDestino,EnvioOK,Assunto,CorpoEmail,[Key])

SELECT  GetDate()
,ZC7_MAILS+';'+ZC7_MAILD
,0
,'ATENÇÃO. Ticket há mais de 48 sem uma interação', 
'O Ticket '+ZC0.ZC0_NUM+' não teve nenhuma interação nas últimas 48 horas.'
,ZC0.ZC0_NUM
FROM ZC0100 AS ZC0 WITH(NOLOCK) 
LEFT JOIN ZC1100 AS ZC1 WITH(NOLOCK) ON ZC1.D_E_L_E_T_='' AND ZC0.ZC0_FILIAL=ZC1.ZC1_FILIAL AND ZC0.ZC0_NUM = ZC1.ZC1_NUM
join	ZC7100 AS ZC7 WITH(NOLOCK) ON ZC7.D_E_L_E_T_='' AND ZC0_ASSUNT = ZC7_ASSUNT AND ZC7_CODARE=ZC0_CODARE  AND ZC7_PROB =ZC0_PROB AND ZC7_UNID=ZC0_UNID
WHERE 
	ZC1.ZC1_NUM IS NULL AND 
	CAST(ZC0.ZC0_DTINC AS DATE)<= CAST(DATEADD(HOUR,-48, GETDATE()) AS DATE)
	and not EXISTS (SELECT 0 FROM TicketsAvisadosSuperiro AS T WITH(NOLOCK) 
					WHERE  T.Ticket = ZC0.ZC0_NUM
					)

insert into TicketsAvisadosSuperiro(Avisado,Ticket) 

select 1
,ZC0.ZC0_NUM
FROM ZC0100 AS ZC0 WITH(NOLOCK) 
LEFT JOIN ZC1100 AS ZC1 WITH(NOLOCK) ON ZC1.D_E_L_E_T_='' AND ZC0.ZC0_FILIAL=ZC1.ZC1_FILIAL AND ZC0.ZC0_NUM = ZC1.ZC1_NUM
join	ZC7100 AS ZC7 WITH(NOLOCK) ON ZC7.D_E_L_E_T_='' AND ZC0_ASSUNT = ZC7_ASSUNT AND ZC7_CODARE=ZC0_CODARE  AND ZC7_PROB =ZC0_PROB AND ZC7_UNID=ZC0_UNID
WHERE 
	ZC1.ZC1_NUM IS NULL AND 
	CAST(ZC0.ZC0_DTINC AS DATE)<= CAST(DATEADD(HOUR,-48, GETDATE()) AS DATE)